questions = [
    {"question": "Who is the current president of Ghana?",
     "A": "Nana Addo",
     "B": "John Dramani Mahama",
     "C": "Bawumia",
     "D": "JJ Rawlings",
     "ans": "John Dramani Mahama",
     "used": False
     },
     {"question": "Which year did Ghana attain independence?",
     "A": "1957",
     "B": "2001",
     "C": "1900",
     "D": "1740",
     "ans": "1957",
     "used": False
     },
     {"question": "Who is the richest man in the world?",
     "A": "Koo Mensah",
     "B": "Elon Musk",
     "C": "Bill gate",
     "D": "Michael Ampomah",
     "ans": "Elon Musk",
     "used": False
     },
     {"question": "Which animal is known as the King of the Jungle?",
     "A": "Leopard",
     "B": "Monkey",
     "C": "Lion",
     "D": "Donkey",
     "ans": "Lion",
     "used": False
     },
     {"question": "How many days are in a week?",
     "A": "Seven",
     "B": "Twelve",
     "C": "Eleven",
     "D": "Ten",
     "ans": "Seven",
     "used": False
     },
     {"question": "How many hours are in a day?",
     "A": "24",
     "B": "16",
     "C": "32",
     "D": "7",
     "ans": "24",
     "used": False
     },
     {"question": "What do bees make?",
     "A": "Bread",
     "B": "Honey",
     "C": "Hausa Koko",
     "D": "Tom Brown",
     "ans": "Honey",
     "used": False
     },
     {"question": "Which of the following shapes has three sides?",
     "A": "Triangle",
     "B": "Circle",
     "C": "None",
     "D": "Pentagon",
     "ans": "Triangle",
     "used": False
     },
     {"question": "Which african country is known for pyramids",
     "A": "Mongolia",
     "B": "Angola",
     "C": "Egypt",
     "D": "Ghana",
     "ans": "Egypt",
     "used": False
     },
     {"question": "Which animal is the largest land animal?",
     "A": "Whale",
     "B": "Cow",
     "C": "Elephant",
     "D": "Dog",
     "ans": "Elephant",
     "used": False
     },
      {"question": "What is the name of the heighest mountain in Ghana?",
     "A": "Everest",
     "B": "Kilmanjaro",
     "C": "Afadjato",
     "D": "Roman Hill",
     "ans": "Afadjato",
     "used": False
     },
     {"question": "How many climate seasons do we have in Ghana",
     "A": "2",
     "B": "4",
     "C": "1",
     "D": "5",
     "ans": "2",
     "used": False
     },
     {"question": "How many regions are in Ghana?",
     "A": "10",
     "B": "12",
     "C": "16",
     "D": "13",
     "ans": "16",
     "used": False
     },
     {"question": "Which of these plants is mostly found in the desert?",
     "A": "Mango",
     "B": "Cactus",
     "C": "Orange",
     "D": "Banana",
     "ans": "Cactus",
     "used": False
     },
     {"question": "Voltage is known as .........",
     "A": "Electron",
     "B": "Electrical power",
     "C": "Electromotive force",
     "D": "Current",
     "ans": "Electromotive force",
     "used": False
     },
     {"question": "Ghana is located in............?",
     "A": "West Africa",
     "B": "East Africa",
     "C": "Damango",
     "D": "Kumasi",
     "ans": "West Africa",
     "used": False
     },
     {"question": "The larva of a butterfly is known as ...........",
     "A": "Catterpillar",
     "B": "Wasp",
     "C": "Beetle",
     "D": "chick",
     "ans": "Catterpillar",
     "used": False
     },
     {"question": "Which of the following shapes has Eight sides?",
     "A": "Hexagon",
     "B": "Heptagon",
     "C": "Octagon",
     "D": "Nonagon",
     "ans": "Octagon",
     "used": False
     }
    
    ]